/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
      },
      colors: {
        primary: '#4d49d9',
        'on-surface-variant': '#416188',
        'on-surface': '#0d3459',
        'on-primary': '#fbf7ff',
        'surface-container-highest': '#d2e4ff',
        background: '#f8f9ff',
        outline: '#5d7da6',
        secondary: '#006d4a',
        'on-tertiary-fixed': '#311c00',
        'inverse-surface': '#000f21',
        'on-tertiary-container': '#4f3000',
        'on-error': '#fff7f7',
        'primary-dim': '#413bcd',
        surface: '#f8f9ff',
        'surface-variant': '#d2e4ff',
        tertiary: '#865400',
        'primary-fixed-dim': '#acabff',
        'on-background': '#0d3459',
        'on-secondary-fixed': '#004930',
        'surface-bright': '#f8f9ff',
        'secondary-container': '#6ffbbe',
        'error-dim': '#770326',
        'on-tertiary': '#fff7f3',
        'on-secondary': '#e6ffee',
        'on-primary-container': '#271ab7',
        error: '#ac3149',
        'on-primary-fixed': '#14008e',
        'secondary-dim': '#005f40',
        'inverse-on-surface': '#8e9eb7',
        'primary-container': '#bcbbff',
        'surface-container': '#e5eeff',
        'on-secondary-container': '#005e3f',
        'surface-tint': '#4d49d9',
        'outline-variant': '#94b4e0',
        'tertiary-fixed': '#fea619',
        'secondary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#ee9800',
        'tertiary-container': '#fea619',
        'on-error-container': '#68001f',
        'primary-fixed': '#bcbbff',
        'surface-container-low': '#eff4ff',
        'surface-dim': '#c4dcff',
        'tertiary-dim': '#764900',
        'inverse-primary': '#8382ff',
        'error-container': '#f76a80',
        'surface-container-high': '#dce9ff',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#5fedb0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
